### PR TITLE
Same functionality, improved Python code.

### PR DESCRIPTION
**Pull request by eric-saintetienne**
Hi Matthias,

Thanks for the video, but the code needs some work, hence this pull request. In broad terms the changes are:
- Rework the code to make it more readable and more pythonesque.
- Fixed markdown syntax in readme
- Fixed direct link to woodgears.ca

Please try it first because I don't have a raspberry Pi, but for testing I used plain files instead, so it should work.  
The easiest for testing is to pull clean from the forked repo at https://github.com/ericsaintetienne/pi_blink_ip

### CODE REVIEW

**Comment by ndbeals** [comment]
Out of curiousity, why are you defining `IPv4_addr` every time within the other function call?

Not like it matters much, seeing how the parent function only gets called once anyways.

**Comment by eric-saintetienne** [comment]
> Out of curiousity, why are you defining `IPv4_addr` every time within the other function call?
> 
> Not like it matters much, seeing how the parent function only gets called once anyways.

For this simple script it doesn't matter much but as a general rule one should aim to reduce possible name collision in a given namespace, and so it's good practice to do declare functions locally.

**Comment by Matthias-Wandel** [comment]
Sorry, won't use this one.
I find this code much less readable, because it's more pytonesque and assumes way more python expertise.  I just wanted to solve the problem, not exercise phthonesqueness.  And less phthonesqueness also makes it more accessible.

For example, I was aware of the crontab library, but decided NOT to use it because it's much more likely that someone knows crontab than knowing crontab AND the library.  Your code is basically a rewrite that makes it twice as big.

README.md changes  - I guess a lot of those tags are redundant, but it was just copied over from the HTML from my website, and I'd like to keep it that way so if I change something, I can just copy it across again.

But you have your "enhanced" branch, so you use that.

**Comment by Matthias-Wandel** [comment]
closed

**Comment by eric-saintetienne** [comment]
I'm not surprised, Matthias, thanks for responding. That tells me a lot about yourself.
Looking forward to see your next video.

**Comment by fairclothjm** [comment]
> Please try it first because I don't have a raspberry Pi, but for testing I used plain files instead, so it should work.

@ericsaintetienne 

In my opinion, this is poor etiquette. Why would you open a PR for a code change that you have not actually tested? Any why would anyone accept a PR from someone that expects others to test it?

**Comment by eric-saintetienne** [comment]
It follows a discussion on YouTube where Matthias asked what he needed to change to improve code quality.

I don't have the hardware but it's not rocket science to mock sysfs. So I did test it, just not with the target hardware.
The poor etiquette would be not to mention it's not tested on real hardware.

Please let me konw how you would have solved this "poor etiquette" conundrum?

It's very common to commit things and expect others to test it when you don't have the hardware to test it. And it's common sense, it shows you don't have much experience in hardware/low-level developement. IRL I am a linux kernel developer and I when I submit a patch I can't test on every architecture. I don't have arm, mips, powerPC and sparc machines in my shed. So when I upstream a patch I test it to the best of my abilities and I expect every architecture maintainer to actually review it, and they do it without even running it most of the time because there is a ginormous number of patches to review. Bu maybe do you think that big names in the linux kernel community who are arch maintainer also have a poor etiquette :)

EDIT I've had a look to your resume and I understand where you're coming from. You don't have much experience in hardware developemnt indeed. I hope your learned something. Everyday is a school day ;)

**Comment by Matthias-Wandel** [comment]
Please point me to where this discussion you refer to happened.  Cause I have no recollection of such a discussion in relation to this program.
That said, if it was a change I wanted, I wouldn't have minded to test it.  I did read through the whole change to see if there was any part of it that I wanted.  But I'm more old school.  Some people prefer to make a problem "go away" by burying it under layers of abstration.  I prefer to minimize it by solving it as simply as possible.

I don't see the "you don't have much experience in hardware development indeed" as being in any way conducive to the discussion.  At any rate *especially* when hardware is involved, there is a good chance that a software change really *needs* testing on the target.

**Comment by eric-saintetienne** [comment]
image

**Comment by Matthias-Wandel** [comment]
Please explain how you got from that to me asking about improving the code.
Someone just saying "poor coding skills" is not being useful to the least, and I wanted him to justify his statement.

**Comment by eric-saintetienne** [comment]
This discussion has reached its end. You have already said you don't want to improve your coding skills and you definitely didn't ask advise from anyone more knowledgeable.
Doing this work was 30 min well spent, it gave me the opportunity to see the real you.
All the best for the future. Like I said earlier, looking forward to your next video.

**Comment by Matthias-Wandel** [comment]
I don't see what you sent me as an "improvement".  I think that is a rather subjective thing.  I would have taken your code and turned it into something shorter to improve it, which of course you would not have agreed with either.

**Pull request closed without merging**
